name: bps_pilani
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0+3
  flutter:
    sdk: flutter
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/i1.jpg"
  android_adaptive_icon: true

flutter:
  uses-material-design: true
  assets:
    - assets/i2.jpg
    - assets/bps.png
    - assets/i1.jpg
    - assets/i3.jpg
    - assets/i4.jpg
    - assets/budha.jpg
    - assets/khandar.jpg
    - assets/columns.jpg
    - assets/qr.png
    - assets/aboutus1.jpg
    - assets/rules1.jpg
    - assets/dhoka.jpg
    - assets/admission.jpg
    - assets/ad1.jpg
    - assets/ad2.jpg

